from django.db import models


class InvoiceItem(models.Model):
    itemSeq = models.IntegerField(default=0.00, null=True)
    itemCd = models.CharField(max_length=100)
    itemClsCd = models.CharField(max_length=100)
    itemNm = models.CharField(max_length=255)
    bcd = models.CharField(max_length=100, blank=True, null=True)
    pkgUnitCd = models.CharField(max_length=10)
    pkg = models.FloatField(default=0.00, null=True)
    qtyUnitCd = models.CharField(max_length=10)
    qty = models.FloatField(default=0.00, null=True)
    prc = models.FloatField(default=0.00, null=True)
    splyAmt = models.FloatField(default=0.00, null=True)
    dcRt = models.FloatField(default=0.00, null=True)
    dcAmt = models.FloatField(default=0.00, null=True)
    isrccCd = models.CharField(max_length=100, blank=True, null=True)
    isrccNm = models.CharField(max_length=255, blank=True, null=True)
    isrcRt = models.FloatField(default=0.00, null=True)
    isrcAmt = models.FloatField(default=0.00, null=True)
    vatCatCd = models.CharField(max_length=10, blank=True, null=True)
    exciseTxCatCd = models.CharField(max_length=10, blank=True, null=True)
    tlCatCd = models.CharField(max_length=10, blank=True, null=True)
    iplCatCd = models.CharField(max_length=10, blank=True, null=True)
    vatTaxblAmt = models.FloatField(default=0.00, null=True)
    vatAmt = models.FloatField(default=0.00, null=True)
    exciseTaxblAmt = models.FloatField(default=0.00, null=True)
    tlTaxblAmt = models.FloatField(default=0.00, null=True)
    iplTaxblAmt = models.FloatField(default=0.00, null=True)
    iplAmt = models.FloatField(default=0.00, null=True)
    tlAmt = models.FloatField(default=0.00, null=True)
    exciseTxAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)
    tax_types = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.itemNm


class Invoice(models.Model):
    tpin = models.CharField(max_length=20)
    bhfId = models.CharField(max_length=10)
    orgInvcNo = models.IntegerField(default=0.00, null=True)
    cisInvcNo = models.CharField(max_length=20)
    custTpin = models.CharField(max_length=20)
    custNm = models.CharField(max_length=255)
    salesTyCd = models.CharField(max_length=10)
    rcptTyCd = models.CharField(max_length=10)
    pmtTyCd = models.CharField(max_length=10)
    salesSttsCd = models.CharField(max_length=10)
    cfmDt = models.CharField(max_length=20)
    salesDt = models.CharField(max_length=20)
    stockRlsDt = models.CharField(max_length=20, blank=True, null=True)
    cnclReqDt = models.CharField(max_length=20, blank=True, null=True)
    cnclDt = models.CharField(max_length=20, blank=True, null=True)
    rfdDt = models.CharField(max_length=20, blank=True, null=True)
    rfdRsnCd = models.CharField(max_length=100, blank=True, null=True)

    totItemCnt = models.IntegerField(default=0.00, null=True)
    taxblAmtA = models.FloatField(default=0.00, null=True)
    taxblAmtB = models.FloatField(default=0.00, null=True)
    taxblAmtC1 = models.FloatField(default=0.00, null=True)
    taxblAmtC2 = models.FloatField(default=0.00, null=True)
    taxblAmtC3 = models.FloatField(default=0.00, null=True)
    taxblAmtD = models.FloatField(default=0.00, null=True)
    taxblAmtRvat = models.FloatField(default=0.00, null=True)
    taxblAmtE = models.FloatField(default=0.00, null=True)
    taxblAmtF = models.FloatField(default=0.00, null=True)
    taxblAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxblAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxblAmtTl = models.FloatField(default=0.00, null=True)
    taxblAmtEcm = models.FloatField(default=0.00, null=True)
    taxblAmtExeeg = models.FloatField(default=0.00, null=True)
    taxblAmtTot = models.FloatField(default=0.00, null=True)

    taxRtA = models.FloatField(default=0.00, null=True)
    taxRtB = models.FloatField(default=0.00, null=True)
    taxRtC1 = models.FloatField(default=0.00, null=True)
    taxRtC2 = models.FloatField(default=0.00, null=True)
    taxRtC3 = models.FloatField(default=0.00, null=True)
    taxRtD = models.FloatField(default=0.00, null=True)
    taxRtRvat = models.FloatField(default=0.00, null=True)
    taxRtE = models.FloatField(default=0.00, null=True)
    taxRtF = models.FloatField(default=0.00, null=True)
    taxRtIpl1 = models.FloatField(default=0.00, null=True)
    taxRtIpl2 = models.FloatField(default=0.00, null=True)
    taxRtTl = models.FloatField(default=0.00, null=True)
    taxRtEcm = models.FloatField(default=0.00, null=True)
    taxRtExeeg = models.FloatField(default=0.00, null=True)
    taxRtTot = models.FloatField(default=0.00, null=True)

    taxAmtA = models.FloatField(default=0.00, null=True)
    taxAmtB = models.FloatField(default=0.00, null=True)
    taxAmtC1 = models.FloatField(default=0.00, null=True)
    taxAmtC2 = models.FloatField(default=0.00, null=True)
    taxAmtC3 = models.FloatField(default=0.00, null=True)
    taxAmtD = models.FloatField(default=0.00, null=True)
    taxAmtRvat = models.FloatField(default=0.00, null=True)
    taxAmtE = models.FloatField(default=0.00, null=True)
    taxAmtF = models.FloatField(default=0.00, null=True)
    taxAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxAmtTl = models.FloatField(default=0.00, null=True)
    taxAmtEcm = models.FloatField(default=0.00, null=True)
    taxAmtExeeg = models.FloatField(default=0.00, null=True)
    taxAmtTot = models.FloatField(default=0.00, null=True)

    totTaxblAmt = models.FloatField(default=0.00, null=True)
    totTaxAmt = models.FloatField(default=0.00, null=True)
    cashDcRt = models.FloatField(default=0.00, null=True)
    cashDcAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    prchrAcptcYn = models.CharField(max_length=1)
    remark = models.TextField(blank=True)
    regrId = models.CharField(max_length=100)
    regrNm = models.CharField(max_length=100)
    modrId = models.CharField(max_length=100)
    modrNm = models.CharField(max_length=100)
    saleCtyCd = models.CharField(max_length=10)
    lpoNumber = models.CharField(max_length=100, blank=True, null=True)
    currencyTyCd = models.CharField(max_length=10)
    exchangeRt = models.CharField(max_length=10)
    destnCountryCd = models.CharField(max_length=10, blank=True, null=True)
    dbtRsnCd = models.CharField(max_length=100, blank=True, null=True)
    invcAdjustReason = models.CharField(max_length=255, blank=True, null=True)

    itemList = models.ManyToManyField(InvoiceItem)
    def __str__(self):
        return f"Invoice #{self.orgInvcNo} - {self.custNm}"

class Credit_Note_Invoice(models.Model):
    tpin = models.CharField(max_length=20)
    bhfId = models.CharField(max_length=10)
    orgSdcId = models.CharField(max_length=10, null=True, blank=True)
    orgInvcNo = models.IntegerField(null=True, blank=True)
    cisInvcNo = models.CharField(max_length=50)
    custTpin = models.CharField(max_length=20)
    custNm = models.CharField(max_length=255)
    salesTyCd = models.CharField(max_length=5)
    rcptTyCd = models.CharField(max_length=5)
    pmtTyCd = models.CharField(max_length=5)
    salesSttsCd = models.CharField(max_length=5)
    cfmDt = models.CharField(max_length=20)
    salesDt = models.CharField(max_length=20)
    stockRlsDt = models.CharField(max_length=20, null=True, blank=True)
    cnclReqDt = models.CharField(max_length=20, null=True, blank=True)
    cnclDt = models.CharField(max_length=20, null=True, blank=True)
    rfdDt = models.CharField(max_length=20, null=True, blank=True)
    rfdRsnCd = models.CharField(max_length=10, null=True, blank=True)
    totItemCnt = models.IntegerField(default=0.00, null=True)
    taxblAmtA = models.FloatField(default=0.00, null=True)
    taxblAmtB = models.FloatField(default=0.00, null=True)
    taxblAmtC1 = models.FloatField(default=0.00, null=True)
    taxblAmtC2 = models.FloatField(default=0.00, null=True)
    taxblAmtC3 = models.FloatField(default=0.00, null=True)
    taxblAmtD = models.FloatField(default=0.00, null=True)
    taxblAmtRvat = models.FloatField(default=0.00, null=True)
    taxblAmtE = models.FloatField(default=0.00, null=True)
    taxblAmtF = models.FloatField(default=0.00, null=True)
    taxblAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxblAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxblAmtTl = models.FloatField(default=0.00, null=True)
    taxblAmtEcm = models.FloatField(default=0.00, null=True)
    taxblAmtExeeg = models.FloatField(default=0.00, null=True)
    taxblAmtTot = models.FloatField(default=0.00, null=True)
    taxRtA = models.FloatField(default=0.00, null=True)
    taxRtB = models.FloatField(default=0.00, null=True)
    taxRtC1 = models.FloatField(default=0.00, null=True)
    taxRtC2 = models.FloatField(default=0.00, null=True)
    taxRtC3 = models.FloatField(default=0.00, null=True)
    taxRtD = models.FloatField(default=0.00, null=True)
    taxRtRvat = models.FloatField(default=0.00, null=True)
    taxRtE = models.FloatField(default=0.00, null=True)
    taxRtF = models.FloatField(default=0.00, null=True)
    taxRtIpl1 = models.FloatField(default=0.00, null=True)
    taxRtIpl2 = models.FloatField(default=0.00, null=True)
    taxRtTl = models.FloatField(default=0.00, null=True)
    taxRtEcm = models.FloatField(default=0.00, null=True)
    taxRtExeeg = models.FloatField(default=0.00, null=True)
    taxRtTot = models.FloatField(default=0.00, null=True)
    taxAmtA = models.FloatField(default=0.00, null=True)
    taxAmtB = models.FloatField(default=0.00, null=True)
    taxAmtC1 = models.FloatField(default=0.00, null=True)
    taxAmtC2 = models.FloatField(default=0.00, null=True)
    taxAmtC3 = models.FloatField(default=0.00, null=True)
    taxAmtD = models.FloatField(default=0.00, null=True)
    taxAmtRvat = models.FloatField(default=0.00, null=True)
    taxAmtE = models.FloatField(default=0.00, null=True)
    taxAmtF = models.FloatField(default=0.00, null=True)
    taxAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxAmtTl = models.FloatField(default=0.00, null=True)
    taxAmtEcm = models.FloatField(default=0.00, null=True)
    taxAmtExeeg = models.FloatField(default=0.00, null=True)
    taxAmtTot = models.FloatField(default=0.00, null=True)
    totTaxblAmt = models.FloatField(default=0.00, null=True)
    totTaxAmt = models.FloatField(default=0.00, null=True)
    cashDcRt = models.FloatField(default=0.00, null=True)
    cashDcAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)
    prchrAcptcYn = models.CharField(max_length=1)
    remark = models.TextField(null=True, blank=True)
    regrId = models.CharField(max_length=50)
    regrNm = models.CharField(max_length=100)
    modrId = models.CharField(max_length=50)
    modrNm = models.CharField(max_length=100)
    saleCtyCd = models.CharField(max_length=10)
    lpoNumber = models.CharField(max_length=50, null=True, blank=True)
    currencyTyCd = models.CharField(max_length=10)
    exchangeRt = models.FloatField(default=0.00, null=True)
    destnCountryCd = models.CharField(max_length=10, null=True, blank=True)
    dbtRsnCd = models.CharField(max_length=10, null=True, blank=True)
    invcAdjust = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return f"Invoice #{self.orgInvcNo} - {self.custNm}"

class Credit_Note_InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items')
    itemSeq = models.IntegerField(default=0.00, null=True)
    itemCd = models.CharField(max_length=50)
    itemClsCd = models.CharField(max_length=50)
    itemNm = models.CharField(max_length=255)
    bcd = models.CharField(max_length=50, null=True, blank=True)
    pkgUnitCd = models.CharField(max_length=50)
    pkg = models.FloatField(default=0.00, null=True)
    qtyUnitCd = models.CharField(max_length=50)
    qty = models.FloatField(default=0.00, null=True)
    prc = models.FloatField(default=0.00, null=True)
    splyAmt = models.FloatField(default=0.00, null=True)
    dcRt = models.FloatField(default=0.00, null=True)
    dcAmt = models.FloatField(default=0.00, null=True)
    isrccCd = models.CharField(max_length=50, null=True, blank=True)
    isrccNm = models.CharField(max_length=255, null=True, blank=True)
    isrcRt = models.FloatField(default=0.00, null=True)
    isrcAmt = models.FloatField(default=0.00, null=True)
    vatCatCd = models.CharField(max_length=10, null=True, blank=True)
    exciseTxCatCd = models.CharField(max_length=10, null=True, blank=True)
    vatTaxblAmt = models.FloatField(default=0.00, null=True)
    exciseTaxblAmt = models.FloatField(default=0.00, null=True)
    vatAmt = models.FloatField(default=0.00, null=True)
    exciseTxAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)


class Debit_Note_Invoice(models.Model):
    tpin = models.CharField(max_length=20)
    bhfId = models.CharField(max_length=10)
    orgInvcNo = models.IntegerField(default=0.00, null=True)
    cisInvcNo = models.CharField(max_length=20)
    custTpin = models.CharField(max_length=20)
    custNm = models.CharField(max_length=100)
    salesTyCd = models.CharField(max_length=5)
    rcptTyCd = models.CharField(max_length=5)
    pmtTyCd = models.CharField(max_length=5)
    salesSttsCd = models.CharField(max_length=5)
    cfmDt = models.CharField(max_length=20)
    salesDt = models.CharField(max_length=20)
    stockRlsDt = models.CharField(max_length=20, null=True, blank=True)
    cnclReqDt = models.CharField(max_length=20, null=True, blank=True)
    cnclDt = models.CharField(max_length=20, null=True, blank=True)
    rfdDt = models.CharField(max_length=20, null=True, blank=True)
    rfdRsnCd = models.CharField(max_length=20, null=True, blank=True)

    totItemCnt = models.IntegerField(default=0.00, null=True)
    # Taxable Amounts
    taxblAmtA = models.FloatField(default=0.00, null=True)
    taxblAmtB = models.FloatField(default=0.00, null=True)
    taxblAmtC1 = models.FloatField(default=0.00, null=True)
    taxblAmtC2 = models.FloatField(default=0.00, null=True)
    taxblAmtC3 = models.FloatField(default=0.00, null=True)
    taxblAmtD = models.FloatField(default=0.00, null=True)
    taxblAmtRvat = models.FloatField(default=0.00, null=True)
    taxblAmtE = models.FloatField(default=0.00, null=True)
    taxblAmtF = models.FloatField(default=0.00, null=True)
    taxblAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxblAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxblAmtTl = models.FloatField(default=0.00, null=True)
    taxblAmtEcm = models.FloatField(default=0.00, null=True)
    taxblAmtExeeg = models.FloatField(default=0.00, null=True)
    taxblAmtTot = models.FloatField(default=0.00, null=True)

    # Tax Rates
    taxRtA = models.FloatField(default=0.00, null=True)
    taxRtB = models.FloatField(default=0.00, null=True)
    taxRtC1 = models.FloatField(default=0.00, null=True)
    taxRtC2 = models.FloatField(default=0.00, null=True)
    taxRtC3 = models.FloatField(default=0.00, null=True)
    taxRtD = models.FloatField(default=0.00, null=True)
    taxRtRvat = models.FloatField(default=0.00, null=True)
    taxRtE = models.FloatField(default=0.00, null=True)
    taxRtF = models.FloatField(default=0.00, null=True)
    taxRtIpl1 = models.FloatField(default=0.00, null=True)
    taxRtIpl2 = models.FloatField(default=0.00, null=True)
    taxRtTl = models.FloatField(default=0.00, null=True)
    taxRtEcm = models.FloatField(default=0.00, null=True)
    taxRtExeeg = models.FloatField(default=0.00, null=True)
    taxRtTot = models.FloatField(default=0.00, null=True)

    # Tax Amounts
    taxAmtA = models.FloatField(default=0.00, null=True)
    taxAmtB = models.FloatField(default=0.00, null=True)
    taxAmtC1 = models.FloatField(default=0.00, null=True)
    taxAmtC2 = models.FloatField(default=0.00, null=True)
    taxAmtC3 = models.FloatField(default=0.00, null=True)
    taxAmtD = models.FloatField(default=0.00, null=True)
    taxAmtRvat = models.FloatField(default=0.00, null=True)
    taxAmtE = models.FloatField(default=0.00, null=True)
    taxAmtF = models.FloatField(default=0.00, null=True)
    taxAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxAmtTl = models.FloatField(default=0.00, null=True)
    taxAmtEcm = models.FloatField(default=0.00, null=True)
    taxAmtExeeg = models.FloatField(default=0.00, null=True)
    taxAmtTot = models.FloatField(default=0.00, null=True)

    totTaxblAmt = models.FloatField(default=0.00, null=True)
    totTaxAmt = models.FloatField(default=0.00, null=True)
    cashDcRt = models.FloatField(default=0.00, null=True)
    cashDcAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    prchrAcptcYn = models.CharField(max_length=1)
    remark = models.TextField(blank=True, null=True)

    regrId = models.CharField(max_length=50)
    regrNm = models.CharField(max_length=50)
    modrId = models.CharField(max_length=50)
    modrNm = models.CharField(max_length=50)

    saleCtyCd = models.CharField(max_length=10)
    lpoNumber = models.CharField(max_length=50, null=True, blank=True)
    currencyTyCd = models.CharField(max_length=10)
    exchangeRt = models.CharField(max_length=20)
    destnCountryCd = models.CharField(max_length=10, blank=True)
    dbtRsnCd = models.CharField(max_length=10)
    invcAdjustReason = models.TextField(default=0.00, null=True)

    def __str__(self):
        return f"Invoice {self.cisInvcNo}"


class Debit_Note_InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='debit_itemList', on_delete=models.CASCADE)

    itemSeq = models.IntegerField(default=0.00, null=True)
    itemCd = models.CharField(max_length=50)
    itemClsCd = models.CharField(max_length=50)
    itemNm = models.CharField(max_length=100)
    bcd = models.CharField(max_length=50, blank=True)
    pkgUnitCd = models.CharField(max_length=10)
    pkg = models.FloatField(default=0.00, null=True)
    qtyUnitCd = models.CharField(max_length=10)
    qty = models.FloatField(default=0.00, null=True)
    prc = models.FloatField(default=0.00, null=True)
    splyAmt = models.FloatField(default=0.00, null=True)
    dcRt = models.FloatField(default=0.00, null=True)
    dcAmt = models.FloatField(default=0.00, null=True)
    isrccCd = models.CharField(max_length=10, blank=True)
    isrccNm = models.CharField(max_length=100, blank=True)
    isrcRt = models.FloatField(default=0.00, null=True)
    isrcAmt = models.FloatField(default=0.00, null=True)
    vatCatCd = models.CharField(max_length=5)
    exciseTxCatCd = models.CharField(max_length=10, blank=True, null=True)
    vatTaxblAmt = models.FloatField(default=0.00, null=True)
    exciseTaxblAmt = models.FloatField(default=0.00, null=True)
    vatAmt = models.FloatField(default=0.00, null=True)
    exciseTxAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    def __str__(self):
        return f"{self.itemNm} ({self.itemCd})"



class LPO_Invoice(models.Model):
    tpin = models.CharField(max_length=20)
    bhfId = models.CharField(max_length=10)
    orgInvcNo = models.IntegerField(default=0.00, null=True)
    cisInvcNo = models.CharField(max_length=20)
    custTpin = models.CharField(max_length=20)
    custNm = models.CharField(max_length=100)
    salesTyCd = models.CharField(max_length=5)
    rcptTyCd = models.CharField(max_length=5)
    pmtTyCd = models.CharField(max_length=5)
    salesSttsCd = models.CharField(max_length=5)
    cfmDt = models.CharField(max_length=20)
    salesDt = models.CharField(max_length=20)
    stockRlsDt = models.CharField(max_length=20, null=True, blank=True)
    cnclReqDt = models.CharField(max_length=20, null=True, blank=True)
    cnclDt = models.CharField(max_length=20, null=True, blank=True)
    rfdDt = models.CharField(max_length=20, null=True, blank=True)
    rfdRsnCd = models.CharField(max_length=20, null=True, blank=True)

    totItemCnt = models.IntegerField(default=0.00, null=True)

    # Taxable Amounts
    taxblAmtA = models.FloatField(default=0.00, null=True)
    taxblAmtB = models.FloatField(default=0.00, null=True)
    taxblAmtC1 = models.FloatField(default=0.00, null=True)
    taxblAmtC2 = models.FloatField(default=0.00, null=True)
    taxblAmtC3 = models.FloatField(default=0.00, null=True)
    taxblAmtD = models.FloatField(default=0.00, null=True)
    taxblAmtRvat = models.FloatField(default=0.00, null=True)
    taxblAmtE = models.FloatField(default=0.00, null=True)
    taxblAmtF = models.FloatField(default=0.00, null=True)
    taxblAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxblAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxblAmtTl = models.FloatField(default=0.00, null=True)
    taxblAmtEcm = models.FloatField(default=0.00, null=True)
    taxblAmtExeeg = models.FloatField(default=0.00, null=True)
    taxblAmtTot = models.FloatField(default=0.00, null=True)

    # Tax Rates
    taxRtA = models.FloatField(default=0.00, null=True)
    taxRtB = models.FloatField(default=0.00, null=True)
    taxRtC1 = models.FloatField(default=0.00, null=True)
    taxRtC2 = models.FloatField(default=0.00, null=True)
    taxRtC3 = models.FloatField(default=0.00, null=True)
    taxRtD = models.FloatField(default=0.00, null=True)
    taxRtRvat = models.FloatField(default=0.00, null=True)
    taxRtE = models.FloatField(default=0.00, null=True)
    taxRtF = models.FloatField(default=0.00, null=True)
    taxRtIpl1 = models.FloatField(default=0.00, null=True)
    taxRtIpl2 = models.FloatField(default=0.00, null=True)
    taxRtTl = models.FloatField(default=0.00, null=True)
    taxRtEcm = models.FloatField(default=0.00, null=True)
    taxRtExeeg = models.FloatField(default=0.00, null=True)
    taxRtTot = models.FloatField(default=0.00, null=True)

    # Tax Amounts
    taxAmtA = models.FloatField(default=0.00, null=True)
    taxAmtB = models.FloatField(default=0.00, null=True)
    taxAmtC1 = models.FloatField(default=0.00, null=True)
    taxAmtC2 = models.FloatField(default=0.00, null=True)
    taxAmtC3 = models.FloatField(default=0.00, null=True)
    taxAmtD = models.FloatField(default=0.00, null=True)
    taxAmtRvat = models.FloatField(default=0.00, null=True)
    taxAmtE = models.FloatField(default=0.00, null=True)
    taxAmtF = models.FloatField(default=0.00, null=True)
    taxAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxAmtTl = models.FloatField(default=0.00, null=True)
    taxAmtEcm = models.FloatField(default=0.00, null=True)
    taxAmtExeeg = models.FloatField(default=0.00, null=True)
    taxAmtTot = models.FloatField(default=0.00, null=True)

    # Totals
    totTaxblAmt = models.FloatField(default=0.00, null=True)
    totTaxAmt = models.FloatField(default=0.00, null=True)
    cashDcRt = models.FloatField(default=0.00, null=True)
    cashDcAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    prchrAcptcYn = models.CharField(max_length=1)
    remark = models.TextField(blank=True, null=True)
    
    regrId = models.CharField(max_length=50)
    regrNm = models.CharField(max_length=50)
    modrId = models.CharField(max_length=50)
    modrNm = models.CharField(max_length=50)

    saleCtyCd = models.CharField(max_length=10)
    lpoNumber = models.CharField(max_length=50, null=True, blank=True)
    currencyTyCd = models.CharField(max_length=10)
    exchangeRt = models.CharField(max_length=20)
    destnCountryCd = models.CharField(max_length=10, blank=True)
    dbtRsnCd = models.CharField(max_length=10, blank=True)
    invcAdjustReason = models.TextField(blank=True)

    def __str__(self):
        return f"Invoice {self.cisInvcNo}"


class LPO_InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='lpo_itemList', on_delete=models.CASCADE)

    itemSeq = models.IntegerField(default=0.00, null=True)
    itemCd = models.CharField(max_length=50)
    itemClsCd = models.CharField(max_length=50)
    itemNm = models.CharField(max_length=100)
    bcd = models.CharField(max_length=50, blank=True)
    pkgUnitCd = models.CharField(max_length=10)
    pkg = models.FloatField(default=0.00, null=True)
    qtyUnitCd = models.CharField(max_length=10)
    qty = models.FloatField(default=0.00, null=True)
    prc = models.FloatField(default=0.00, null=True)
    splyAmt = models.FloatField(default=0.00, null=True)
    dcRt = models.FloatField(default=0.00, null=True)
    dcAmt = models.FloatField(default=0.00, null=True)
    vatCatCd = models.CharField(max_length=5)
    vatTaxblAmt = models.FloatField(default=0.00, null=True)
    vatAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    def __str__(self):
        return f"{self.itemNm} ({self.itemCd})"


class Export_Invoice(models.Model):
    tpin = models.CharField(max_length=20)
    bhfId = models.CharField(max_length=10)
    orgInvcNo = models.IntegerField(default=0.00, null=True)
    cisInvcNo = models.CharField(max_length=20)
    custTpin = models.CharField(max_length=20)
    custNm = models.CharField(max_length=100)
    salesTyCd = models.CharField(max_length=5)
    rcptTyCd = models.CharField(max_length=5)
    pmtTyCd = models.CharField(max_length=5)
    salesSttsCd = models.CharField(max_length=5)

    cfmDt = models.CharField(max_length=20)
    salesDt = models.CharField(max_length=20)
    stockRlsDt = models.CharField(max_length=20, null=True, blank=True)
    cnclReqDt = models.CharField(max_length=20, null=True, blank=True)
    cnclDt = models.CharField(max_length=20, null=True, blank=True)
    rfdDt = models.CharField(max_length=20, null=True, blank=True)
    rfdRsnCd = models.CharField(max_length=20, null=True, blank=True)

    totItemCnt = models.IntegerField(default=0.00, null=True)

    # Taxable amounts
    taxblAmtA = models.FloatField(default=0.00, null=True)
    taxblAmtB = models.FloatField(default=0.00, null=True)
    taxblAmtC1 = models.FloatField(default=0.00, null=True)
    taxblAmtC2 = models.FloatField(default=0.00, null=True)
    taxblAmtC3 = models.FloatField(default=0.00, null=True)
    taxblAmtD = models.FloatField(default=0.00, null=True)
    taxblAmtRvat = models.FloatField(default=0.00, null=True)
    taxblAmtE = models.FloatField(default=0.00, null=True)
    taxblAmtF = models.FloatField(default=0.00, null=True)
    taxblAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxblAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxblAmtTl = models.FloatField(default=0.00, null=True)
    taxblAmtEcm = models.FloatField(default=0.00, null=True)
    taxblAmtExeeg = models.FloatField(default=0.00, null=True)
    taxblAmtTot = models.FloatField(default=0.00, null=True)

    # Tax rates
    taxRtA = models.FloatField(default=0.00, null=True)
    taxRtB = models.FloatField(default=0.00, null=True)
    taxRtC1 = models.FloatField(default=0.00, null=True)
    taxRtC2 = models.FloatField(default=0.00, null=True)
    taxRtC3 = models.FloatField(default=0.00, null=True)
    taxRtD = models.FloatField(default=0.00, null=True)
    taxRtRvat = models.FloatField(default=0.00, null=True)
    taxRtE = models.FloatField(default=0.00, null=True)
    taxRtF = models.FloatField(default=0.00, null=True)
    taxRtIpl1 = models.FloatField(default=0.00, null=True)
    taxRtIpl2 = models.FloatField(default=0.00, null=True)
    taxRtTl = models.FloatField(default=0.00, null=True)
    taxRtEcm = models.FloatField(default=0.00, null=True)
    taxRtExeeg = models.FloatField(default=0.00, null=True)
    taxRtTot = models.FloatField(default=0.00, null=True)

    # Tax amounts
    taxAmtA = models.FloatField(default=0.00, null=True)
    taxAmtB = models.FloatField(default=0.00, null=True)
    taxAmtC1 = models.FloatField(default=0.00, null=True)
    taxAmtC2 = models.FloatField(default=0.00, null=True)
    taxAmtC3 = models.FloatField(default=0.00, null=True)
    taxAmtD = models.FloatField(default=0.00, null=True)
    taxAmtRvat = models.FloatField(default=0.00, null=True)
    taxAmtE = models.FloatField(default=0.00, null=True)
    taxAmtF = models.FloatField(default=0.00, null=True)
    taxAmtIpl1 = models.FloatField(default=0.00, null=True)
    taxAmtIpl2 = models.FloatField(default=0.00, null=True)
    taxAmtTl = models.FloatField(default=0.00, null=True)
    taxAmtEcm = models.FloatField(default=0.00, null=True)
    taxAmtExeeg = models.FloatField(default=0.00, null=True)
    taxAmtTot = models.FloatField(default=0.00, null=True)

    # Totals
    totTaxblAmt = models.FloatField(default=0.00, null=True)
    totTaxAmt = models.FloatField(default=0.00, null=True)
    cashDcRt = models.FloatField(default=0.00, null=True)
    cashDcAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    prchrAcptcYn = models.CharField(max_length=1)
    remark = models.TextField(blank=True, null=True)

    regrId = models.CharField(max_length=50)
    regrNm = models.CharField(max_length=50)
    modrId = models.CharField(max_length=50)
    modrNm = models.CharField(max_length=50)

    saleCtyCd = models.CharField(max_length=10)
    lpoNumber = models.CharField(max_length=50, null=True, blank=True)
    currencyTyCd = models.CharField(max_length=10)
    exchangeRt = models.CharField(max_length=20)

    destnCountryCd = models.CharField(max_length=10, blank=True)
    dbtRsnCd = models.CharField(max_length=10, blank=True)
    invcAdjustReason = models.TextField(blank=True)

    def __str__(self):
        return f"Invoice {self.cisInvcNo}"


class Export_InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='export_itemList', on_delete=models.CASCADE)

    itemSeq = models.IntegerField(default=0.00, null=True)
    itemCd = models.CharField(max_length=50)
    itemClsCd = models.CharField(max_length=50)
    itemNm = models.CharField(max_length=100)
    bcd = models.CharField(max_length=50, blank=True)

    pkgUnitCd = models.CharField(max_length=10)
    pkg = models.FloatField(default=0.00, null=True)
    qtyUnitCd = models.CharField(max_length=10)
    qty = models.FloatField(default=0.00, null=True)
    prc = models.FloatField(default=0.00, null=True)
    splyAmt = models.FloatField(default=0.00, null=True)
    dcRt = models.FloatField(default=0.00, null=True)
    dcAmt = models.FloatField(default=0.00, null=True)

    # Added tax and source-related fields
    isrccCd = models.CharField(max_length=20, blank=True)
    isrccNm = models.CharField(max_length=100, blank=True)
    isrcRt = models.FloatField(default=0.00, null=True)
    isrcAmt = models.FloatField(default=0.00, null=True)

    vatCatCd = models.CharField(max_length=5)
    exciseTxCatCd = models.CharField(max_length=20, blank=True, null=True)
    vatTaxblAmt = models.FloatField(default=0.00, null=True)
    exciseTaxblAmt = models.FloatField(default=0.00, null=True)
    vatAmt = models.FloatField(default=0.00, null=True)
    exciseTxAmt = models.FloatField(default=0.00, null=True)
    totAmt = models.FloatField(default=0.00, null=True)

    def __str__(self):
        return f"{self.itemNm} ({self.itemCd})"
