# Generated by Django 5.2 on 2025-04-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spplrTpin', models.CharField(max_length=15)),
                ('spplrNm', models.CharField(max_length=255)),
                ('spplrBhfId', models.CharField(max_length=10)),
                ('spplrInvcNo', models.IntegerField()),
                ('rcptTyCd', models.CharField(max_length=10)),
                ('pmtTyCd', models.CharField(max_length=10)),
                ('cfmDt', models.DateTimeField()),
                ('salesDt', models.CharField(max_length=8)),
                ('stockRlsDt', models.DateTimeField(blank=True, null=True)),
                ('totItemCnt', models.IntegerField()),
                ('totTaxblAmt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('totTaxAmt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('totAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSeq', models.IntegerField()),
                ('itemCd', models.CharField(max_length=50)),
                ('itemClsCd', models.CharField(max_length=50)),
                ('itemNm', models.CharField(max_length=255)),
                ('bcd', models.CharField(blank=True, max_length=50, null=True)),
                ('pkgUnitCd', models.CharField(max_length=50)),
                ('pkg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qtyUnitCd', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('splyAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dcRt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dcAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vatCatCd', models.CharField(max_length=50)),
                ('iplCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('tlCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('exciseTxCatCd', models.CharField(blank=True, max_length=50, null=True)),
                ('vatTaxblAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exciseTaxblAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iplTaxblAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tlTaxblAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxblAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vatAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iplAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tlAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exciseTxAmt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_itemList', to='purchases.purchase')),
            ],
        ),
    ]
