# Generated by Django 5.2 on 2025-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskCd', models.CharField(max_length=20)),
                ('dclDe', models.CharField(blank=True, max_length=10, null=True)),
                ('itemSeq', models.IntegerField()),
                ('dclNo', models.CharField(max_length=50)),
                ('hsCd', models.CharField(max_length=20)),
                ('itemNm', models.CharField(max_length=100)),
                ('imptItemsttsCd', models.CharField(max_length=10)),
                ('orgnNatCd', models.CharField(max_length=5)),
                ('exptNatCd', models.CharField(max_length=5)),
                ('pkg', models.IntegerField()),
                ('pkgUnitCd', models.CharField(blank=True, max_length=10, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtyUnitCd', models.CharField(max_length=10)),
                ('totWt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('netWt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spplrNm', models.TextField()),
                ('agntNm', models.CharField(max_length=100)),
                ('invcFcurAmt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invcFcurCd', models.CharField(max_length=10)),
                ('invcFcurExcrt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
