# Generated by Django 5.2 on 2025-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNm', models.CharField(max_length=255, verbose_name='Item Name')),
                ('itemCd', models.CharField(max_length=255, verbose_name='Item Code')),
                ('itemClsCd', models.CharField(max_length=255, verbose_name='Item Class Code')),
                ('itemTyCd', models.CharField(max_length=255, verbose_name='Item Type Code')),
                ('orgnNatCd', models.CharField(max_length=255, verbose_name='Country Of Origin')),
                ('pkgUnitCd', models.CharField(max_length=100, verbose_name='Packing Unit')),
                ('qtyUnitCd', models.CharField(max_length=100, verbose_name='QTY Unit')),
                ('vatCatCd', models.CharField(max_length=100, verbose_name='Tax Type Unit')),
                ('iplCatCd', models.CharField(max_length=100, verbose_name='IPL Category Code')),
                ('tlCatCd', models.CharField(max_length=100, verbose_name='TL Category Code')),
                ('exciseTxCatCd', models.CharField(max_length=100, verbose_name='Excise Tax Category Code')),
            ],
        ),
    ]
