# Generated by Django 5.2 on 2025-04-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpin', models.CharField(max_length=15)),
                ('bhfId', models.CharField(max_length=10)),
                ('sarNo', models.IntegerField()),
                ('orgSarNo', models.IntegerField()),
                ('regTyCd', models.CharField(max_length=10)),
                ('custTpin', models.CharField(blank=True, max_length=15, null=True)),
                ('custNm', models.CharField(blank=True, max_length=255, null=True)),
                ('custBhfId', models.CharField(blank=True, max_length=10, null=True)),
                ('sarTyCd', models.CharField(max_length=10)),
                ('ocrnDt', models.CharField(max_length=8)),
                ('totItemCnt', models.IntegerField()),
                ('totTaxblAmt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('totTaxAmt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('totAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('regrId', models.CharField(max_length=50)),
                ('regrNm', models.CharField(max_length=255)),
                ('modrNm', models.CharField(max_length=255)),
                ('modrId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SAR_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSeq', models.IntegerField()),
                ('itemCd', models.CharField(max_length=50)),
                ('itemClsCd', models.CharField(max_length=50)),
                ('itemNm', models.CharField(max_length=255)),
                ('pkgUnitCd', models.CharField(max_length=50)),
                ('qtyUnitCd', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('splyAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxblAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vatCatCd', models.CharField(max_length=50)),
                ('taxAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totAmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_itemList', to='sar.sar')),
            ],
        ),
    ]
