# Generated by Django 5.2 on 2025-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, null=True, verbose_name='T-Pin')),
                ('bhfId', models.CharField(max_length=255, null=True, verbose_name='Your Name')),
            ],
        ),
    ]
