# Generated by Django 5.2 on 2025-04-16 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initialization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpin', models.CharField(max_length=100, null=True, verbose_name='T-Pin')),
                ('taxprNm', models.CharField(max_length=255, null=True, verbose_name='Your Name')),
                ('bsnsActv', models.CharField(max_length=255, null=True, verbose_name='Your Business Activity')),
                ('bhfId', models.CharField(max_length=50, null=True, verbose_name='Branch ID')),
                ('bhfNm', models.CharField(max_length=255, null=True, verbose_name='Branch Name')),
                ('bhfOpenDt', models.DateField(default=datetime.date.today, null=True, verbose_name='Initialized On')),
                ('prvncNm', models.CharField(max_length=100, null=True, verbose_name='Business Province')),
                ('dstrtNm', models.CharField(max_length=100, null=True, verbose_name='Business District')),
                ('sctrNm', models.CharField(max_length=100, null=True, verbose_name='Business Sector')),
                ('dvcid', models.CharField(max_length=100, null=True, verbose_name='Device ID')),
                ('vsdc_url', models.CharField(max_length=100, null=True, verbose_name='VSDC URL')),
            ],
        ),
    ]
